# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
  
    
    - task: replacetokens@4
      inputs:
        rootDirectory: '$(Build.SourcesDirectory)/database/'
        targetFiles: 'Dockerfile'
        encoding: 'auto'
        tokenPattern: 'azpipelines'
        writeBOM: false
        actionOnMissing: 'warn'
        keepToken: false
        actionOnNoFiles: 'continue'
        enableTransforms: false
        enableRecursion: false
        useLegacyPattern: false
        enableTelemetry: true
        
    - task: replacetokens@4
      inputs:
        rootDirectory: '$(Build.SourcesDirectory)/backend/'
        targetFiles: 'conexao.php'
        encoding: 'auto'
        tokenPattern: 'azpipelines'
        writeBOM: false
        actionOnMissing: 'warn'
        keepToken: false
        actionOnNoFiles: 'continue'
        enableTransforms: false
        enableRecursion: false
        useLegacyPattern: false
        enableTelemetry: true
        
    - task: Docker@2
      name: buildBackend
      inputs:
        containerRegistry: 'ea'
        repository: '142129/projeto-backend'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/backend/Dockerfile'
        tags: '1.0'
              
    - task: Docker@2
      name: buildDatabase
      inputs:
        containerRegistry: 'ea'
        repository: '142129/projeto-database'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/database/Dockerfile'
        tags: '1.0'
